apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-api
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: ecommerce-api
  template:
    metadata:
      labels:
        app: ecommerce-api
    spec:
      containers:
      - name: api
        image: registry.digitalocean.com/ecommerce-go/go-hello:latest
        envFrom:
        - configMapRef:
            name: ecommerce-env
        - secretRef:
            name: ecommerce-secret
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
